name = input("What is your hero's name? ")
enemy = input("Who is your hero's greatest enemy? ")
power = input("What is your super power? ")
city = input("What is the city they protect? ")
food = input("What is the food that gives them powers? ")
print("Hello!", name, "your ability", power, "will make sure you")
print("never have to look at", enemy, "again.","go eat", food)
print("as you walk down the streets of", city,"and use", power, "for good and not evil!")