myname = input("What is your name?: ")
food = input("What is your favorite food?: ")
music = input("What is your favorite song right now?: ")
location = input("What is your zipcode for tickets near you!?!?!? ")
print(myname)
print ("CONGRATZ! the winning food was")
print(food)
print(" Becuase you guessed the right food you have won a ticket to see")
print(music)
print(" the soonest show near your location in")
print(location)
print("is Febuary")